openapi: 3.0.0
info:
  title: TechCare Admin API
  description: API para gerenciamento do painel administrativo TechCare
  version: 1.0.0
  contact:
    name: Equipe TechCare
    email: suporte@techcare.com

servers:
  - url: /api/v1
    description: Servidor de produção

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [admin, tecnico, visualizador]
        data_criacao:
          type: string
          format: date-time

    Servico:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
          enum: [running, stopped, error]
        ultima_atualizacao:
          type: string
          format: date-time

paths:
  /usuarios:
    get:
      summary: Lista todos os usuários
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
        '401':
          description: Não autorizado

    post:
      summary: Criar novo usuário
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuário criado com sucesso
        '400':
          description: Dados inválidos
        '401':
          description: Não autorizado

  /servicos:
    get:
      summary: Listar status dos serviços
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de serviços
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Servico'
        '401':
          description: Não autorizado

    post:
      summary: Iniciar/Parar serviço
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                servico_id:
                  type: integer
                acao:
                  type: string
                  enum: [start, stop, restart]
      responses:
        '200':
          description: Ação executada com sucesso
        '400':
          description: Ação inválida
        '401':
          description: Não autorizado
